### ISSUE TITLE
Support other types languages

### ISSUE THREAD

**Issue by texastoland** [shikijs/twoslash#49]
This is probably outside the scope of Shiki-Twoslash's [vision](https://github.com/shikijs/twoslash/blob/main/VISION.md#shiki-twoslash) and too narrow in usefulness. It seems like alternative parsers (e.g. AssmeblyScript, Dart, ReScript) could be implemented by conforming to `twoslasher`'s signature. `TwoSlashReturn` seems sufficiently general at first glance.

**Comment by orta** [comment]
Yeah, I agree - I think someone could use Shiki Twoslash as a template and really focus on _just_ LSP support and they could get a tonne of value across many programming ecosystems with it.

The tricky bit is that you need to be able to reliably set up a virtual project for each of them to be able to make the correct queries, and that's difficult. So, I could see a plugin-like system where you can easily add rich support for a language in a plugin.

That said, I need to keep shiki-twoslash focused (in order to also maintain many other things) which is why the vision is constrained there, so it's a good idea for someone else to take!

**Comment by texastoland** [comment]
> I need to keep shiki-twoslash focused

I assumed so!

I'll open a PR to propose making `twoslasher`'s import dynamic if I experiment with it successfully later 🤙🏼
